#%RAML 1.0
title: GardenCast 
baseUri:
version: v1
protocols: [ HTTP, HTTPS ]
documentation:
 - title: Home
   content: |
     Welcome to the _GardenCast API_ Documentation. The _GardenCast API_
     allows you to connect your application to recieve weather data
     and information about plants, weather and a custom search.
mediaType: 
- application/json


/weather:
  description: retrieves information about weather. **NOTE** All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the id parameter) will                  provide the most precise location results.
  get:
    queryParameters:
      lat:
        displayName: Latitude
        type: number
        description: geographical latitude
        example:
          50.3135
        required: false

      long:
        displayName: Longitude
        type: number
        description: geographical longitude
        example:
          11.9128
        required: false

      cityID:
        displayName: City ID
        type: number
        description: City ID. You can call by city ID. API responds with exact result. The List of city IDs can be downloaded [here](http://bulk.openweathermap.org/sample/).                                         You can include multiple cities in parameter &mdash; just separate them by commas
        example:
          2172797
        required: false

      cityName:
        displayName: City Name
        type: string
        description: City Name. You can call by city name, or by city name and country code. The API responds with a list of results that match a searching word. For the query value, type the                       city name and optionally the country code divided by comma
        example:
          Hof
        required: false

      zipCode:
        displayName: ZIP Code
        type: string
        description: Search by zip code. Please note if country is not specified then the search works for GER as a default."
        example:
          95025,ger
        required: false

    responses:
      200:
        description: SUCCESS
        body:
          application/json:

            example:
              {
                "current" : {
                  "time" : 1595243443,
                  "sunrise" : 1595243663,
                  "sunset": 1595296278,
                  "temp": 293.28,
                  "feels_like": 293.82,
                  "humidity": 100,
                  "uvi": 10.64,
                  "clouds": 90,
                  "weather" : [
                    {
                      "id" : 501,
                      "main" : "Rain",
                      "description" : "moderate rain"
                    },
                    {
                      "id" : 201,
                      "main" : "Thunderstorm",
                      "description" : "thunderstorm with rain"                      
                    }
                  ],
                  "hourly" : [
                    {
                      "time": 1595242800,
                      "temp": 293.28,
                      "feels_like": 293.82,
                      "humidity": 100,
                      "clouds": 90,
                  "weather" : [
                        {
                        "id" : 501,
                        "main" : "Rain",
                        "description" : "moderate rain"
                        }
                     ]
                    }
                  ],
                  "daily" : [
                    {
                      "time" : 1595268000,
                      "sunrise" : 1595243663,
                      "sunset": 1595296278,
                      "humidity" : 100,
                      "cloud" : 97,
                      "uvi" : 10,
                      "temp" : {
                        "day" : 30,
                        "min" : 30,
                        "max" : 30,
                        "night" : 30,
                        "eve" : 30,
                        "morn" : 30
                      },
                      "feels_like" : {
                        "day" : 30,
                        "night" : 30,
                        "eve" : 30,
                        "morn" : 30
                      },
                    }
                  ],
                  "alerts" : [
                      {
                        "event" : "Heat Advisory",
                        "start_Time" : 1597341600,
                        "end_Time" : 1597366800,
                        "description" : HEAT ADVISORY REMAINS IN EFFECT FROM 1 PM THIS AFTERNOON TO\n8 PM CDT THIS EVENING...\n* WHAT...Heat index values of 105 to 109 degrees expected.\n*                                             WHERE...Creek, Okfuskee, Okmulgee, McIntosh, Pittsburg,\nLatimer, Pushmataha, and Choctaw Counties.\n* WHEN...From 1 PM to 8 PM CDT Thursday.\n*                                                 IMPACTS...The combination of hot temperatures and high\nhumidity will combine to create a dangerous situation in which\nheat illnesses are possible."
                      }
                  ]
                }
              }


      400:
        description: BAD REQUEST, CHECK PARAMETERS
        body:
          application/json:
            example:
              {
                data: {
                  code: 400,
                  info: "Bad Request"
                } 
              }
      401:
        description: Unauthorized
        body:
          application/json:
            example:
              {
                data: {
                  code: 401,
                  info: "Client not authenticated"
                } 
              }

/notesForPlants:
  description: this endpoint can be used in two ways. Call it with weather information to recieve plants that are affected by this weather. Or call by plants and get back weather information corresponding to the plant that was called. Its also possible to input a month and recieve a list of plants to best plant during this month.
  get:
    queryParameters:
      minTemperature:
        displayName: Minimum Temperature
        type: number
        description: The minimum tolerable temperature for the species. In celsius or fahrenheit degrees
        example:
          -10
        required: false
        
      maxTemperature:
        displayName: Maximum Temperature
        type: number
        description: The maximum tolerable temperature for the species. In celsius or fahrenheit degrees
        example:
          30
        required: false

      months:
        displayName: Months
        type: string
        description: The most active growth months of the species (usually all year round for perennial plants)
        example:
          April
        required: false

    responses:
      200:
        description: SUCCESS
        body:
          application/json:
            example:
              {
                "ideasForPlanting" : [
                  {
                    "id" : 103926,
                    "common_name" : Fynbos aloe,
                    "slug": "aloe-succotrina",
                    "scientific_name": "Aloe vera",
                    "family": null,
                    "image_url" : "https://bs.floristic.org/image/o/e96639b99cee09e6b7b9faa4901ee6cd54e8519b",
                    "notesForPlanting" : "requires a lot of water",
                    "fertility_requirement" : null,
                    "minimum temperature" : 21,
                    "maximum_temperature" : 30,
                    "atmospheric_humidity" : 2
                  },
                  {
                    "id" : 103926,
                    "common_name" : Fynbos aloe,
                    "slug": "aloe-succotrina",
                    "scientific_name": "Aloe vera",
                    "family": null,
                    "image_url" : "https://bs.floristic.org/image/o/e96639b99cee09e6b7b9faa4901ee6cd54e8519b",
                    "notesForPlanting" : "requires a lot of water",
                    "fertility_requirement" : null,
                    "minimum temperature" : 21,
                    "maximum_temperature" : 30,
                    "atmospheric_humidity" : 2
                  },
                ]
              }
      400:
        description: BAD REQUEST, CHECK PARAMETERS
        body:
          application/json:
            example:
              {
                data: {
                  code: 400,
                  info: "Bad Request"
                } 
              }
      401:
        description: Unauthorized
        body:
          application/json:
            example:
              {
                data: {
                  code: 401,
                  info: "Client not authenticated"
                } 
              }


/bestPlantedIn:
  description: this endpoint can be used to retrieve a list of months in which the specified plant is best to be planted along with other useful information for caretaking
  get:
    queryParameters:
      plantName:
        displayName: Plant Name
        type: string
        description: The name of the plant according to which the months will be displayed
        example:
          Aloe Vera
        required: true

    responses:
      200:
        description: SUCCESS
        body:
          application/json:
            example:
              {
                "plant_name" : Aloe Vera,
                "listOfMonths" : [
                  april, may, june, july
                ],
                "notesForCaretaking" : {
                  "descriptionOfGrowth" : A description on how the plant usually grows,
                  "sowing" : A description on how to sow the plant,
                  "ph_maximum" : The maximum acceptable soil pH (of the top 30 centimeters of soil) for the plant,
                  "ph_minimum" : The minimum acceptable soil pH (of the top 30 centimeters of soil) for the plant,
                  "light" : Required amount of light, on a scale from 0 (no light, smaller 10 lux) to 10 (very intensive insolation, higher 100 000 lux),
                  "bloom_months" : The months the species usually blooms,
                  "row_spacing" : The minimum spacing between each rows of plants, in centimeters
                }
              }
      400:
        description: BAD REQUEST, CHECK PARAMETERS
        body:
          application/json:
            example:
              {
                data: {
                  code: 400,
                  info: "Bad Request"
                } 
              }
      401:
        description: Unauthorized
        body:
          application/json:
            example:
              {
                data: {
                  code: 401,
                  info: "Client not authenticated"
                } 
              }
