#%RAML 1.0 DataType
type: object
properties:
  id: number
  common_name: string
  slug: string
  scientific_name: string
  year: number
  author: string
  status: string
  family_common_name: string
  image_url: string
  genus: string
  family: string
