#%RAML 1.0 NamedExample
    value:
     id: 103926
     common_name: Fynbos aloe
     slug: aloe-succotrina
     scientific_name: Aloe vera
     year: 1770
     author: Weston
     status: accepted
     family_common_name: "null"
     image_url: https://bs.floristic.org/image/o/e96639b99cee09e6b7b9faa4901ee6cd54e8519b
     genus: Aloe
     family: Asphodelaceae

     