#%RAML 1.0 NamedExample
value:
  name: latin name
  confidence: 0.82
  taxonomy:
    kingdom: kingdom name
    subkingdom: subkingdom name
    division: division name
    division_order: division order name
    family: family name
    genus: genus name
    plant: plant name
  image: base643nc0drd1m4g3
  synonyms:
    - plantname 1
    - plantname 2
  
        
    
